### ISSUE TITLE
On Linux, when you create a new welded part, it doesn't go into the expected folder

### ISSUE THREAD

**Issue by girka2k** [UbioWeldingLtd/UbioWeldContinued#16]
On Linux, when you create a new welded part, it doesn't go into the expected folder (~/.local/share/Steam/steamapps/common/Kerbal\ Space\ Program/GameData/UbioWeldingLtd/Parts/) but instead a wholly new directory outside the Steam tree, and instead rooted on the user's home directory. The parts end up in ~/GameData/UbioWeldingLtd/Parts/.

http://forum.kerbalspaceprogram.com/threads/107273-0-90-UbioZur-Welding-Ltd-Continued-2-1-1-%282015-01-14%29?p=1818166&viewfull=1#post1818166

https://www.dropbox.com/s/9qkn1kzm32rt6fi/7-node_linux_path_debug_KSP-2015-04-02.log?dl=0

**Comment by dertroglodyt** [comment]
Seems fixed (2.2.0). At least on my ubuntu it saves into correct folder.

**Comment by Alewx** [comment]
That is great, but did you use Ubuntu before?

**Comment by dertroglodyt** [comment]
I used Ubuntu before ;-) but just installed the welding mod (2.2.0). So I can't tell if it behaved differently in earlier versions on Ubuntu.

**Comment by Alewx** [comment]
I will then mark it as fixed by temporary.
