### ISSUE TITLE
tweak scale support

### ISSUE THREAD

**Issue by dertroglodyt** [UbioWeldingLtd/UbioWeldContinued#31]
A great improvement would be if you could take tweak scale scaling into account.
This would open up so much more options.

**Comment by Alewx** [comment]
do you mean the addition of the module or just the scaling of the actual parts in the editor?

**Comment by dertroglodyt** [comment]
Personaly I'm all about optics. So retaining scaling would be sufficient I guess.

**Comment by Alewx** [comment]
I will deploy my latest changes for 2.2.0 dev version then the scaling should finally be working properly.

**Comment by dertroglodyt** [comment]
Excellent! For me that's the most important feature directly after being able to weld at all. Thanks.

**Comment by dertroglodyt** [comment]
One more glitch: Saving scaled objects as a sub assembly and then using the sub assembly and welding it keeps the objects visually the correct size but tanks have fuel (and weight) of 100% item.
Building and scaling without saving as sub assembly has the exact opposite effects.

**Comment by Alewx** [comment]
that might be a problem at the sub assembly, but best is you test it after I released the newest dev version.

**Comment by dertroglodyt** [comment]
New version has the optical scaling right now in both cases.
But tank contents are for 100% in both cases too. Therefore mass is of too.
So, close but not quite. ;-)

**Comment by Alewx** [comment]
Is this in Subassemblies or direct?

**Comment by dertroglodyt** [comment]
subassemblies and direct building now has identical behavior.
optical scaling is correct, tank contect and mass are wrong for both.

**Comment by Alewx** [comment]
Ok I used the 1.0.4 Version and can not reprocude the Thing you are telling me.
I made two parts one was 2.5m and one was 3.75m in Diameter, and the resources and the dry mass were updated correct in the weldments.
LF OX MP EL were all correct increased.

**Comment by dertroglodyt** [comment]
Did some more testing.
Sorry, my bad. Didn't realize that contents are only wrong for tanks with ModularFuelTanks content.
Stock tanks without variable content seem to fine.
Of cause it would be cool to use ModularFuelTanks too. Wink, wink. ;-)

Strangely the nodes on tanks seem to wander inside when welded. The longer the tank, the deeper inside. See here: http://i.imgur.com/qOGL9yo.png

**Comment by Alewx** [comment]
hmm strange, maybe the nodes are not taken live but from config.
MFT oh my, time to look at that :(

**Comment by dertroglodyt** [comment]
Just to be sure, I tested again on a blank vanilla install.
Same wandering nodes issues.
Plus I noticed they should only touch not intersect: http://i.imgur.com/6QEi0qh.png

**Comment by Alewx** [comment]
Oh man you dig up some crazy stuff :D
Blank vanilla so not even tweakscale, no nothing?

**Comment by dertroglodyt** [comment]
Vanilla. Nothing but Welding in GameData.

**Comment by Alewx** [comment]
The corner tank looks so much smaller compared to the others.

**Comment by dertroglodyt** [comment]
Compared welded tank stack to unwelded.
"Good" news: Placing and nodes are most certainly correct. (Hard to check but seems to fit "by eye")
The tanks hull is visually bigger then it should be.

**Comment by dertroglodyt** [comment]
Left side welded: http://i.imgur.com/hgJrDv0.png
Back welded: http://i.imgur.com/6cfT7gB.png

**Comment by dertroglodyt** [comment]
Nodes of welded in front of unwelded stack: http://i.imgur.com/ALBcfB1.png

**Comment by dertroglodyt** [comment]
After more testing:
On the plus side symmetry, manual rotation and manual translation seem to be correct.

Now the weird stuff:
Welding a previously welded part to a new vanilla blows up the vanilla (like before) but _shrinks_ the already welded one to smaller than vanilla size.
Vanilla T800 with welded part on top. before welding: http://i.imgur.com/Z2Rhk5C.png
After welding and placing on top of another vanilla T800: http://i.imgur.com/dnVXgTv.png
Nodes and centre of shrinked parts still are placed correctly.

**Comment by dertroglodyt** [comment]
Aaaaaand more testing.
The blow up bug only seems to show up for FL-Txxx tanks and the mk1 liquid fuel fuselage (which shrinks upon welding). All other tanks are totaly fine.
Vanilla tanks placed on top of there welded counterpart: http://i.imgur.com/uxWj0KO.png

**Comment by Alewx** [comment]
welding welded parts again is something that is broken, and so far not fixable, there is only the way of welding regular parts or weldments again, and so far it is more needed to weld regular parts correct.

**Comment by Alewx** [comment]
Ok the wrong scaling in optical is happending due to some reduction in useless values of the weldment, but Looks like there they are Need so I try to fix them.

About the MFT that will be something for 2.3 nothing in 2.2

**Comment by Alewx** [comment]
So another update that hopefully now fixed it without breaking anything else, please test it again.

**Comment by dertroglodyt** [comment]
Hmmm, I don't see anything new committed...

**Comment by Alewx** [comment]
It is in my own repository, but the release is updated.

**Comment by dertroglodyt** [comment]
Vanilla and Vanilla + TweakScale both seem perfect now.
Going to test sub assemblies later today.

**Comment by Alewx** [comment]
puh, what a release, that really drove me crazy.

**Comment by dertroglodyt** [comment]
Sub assemblies seem perfect too. Nice work, thanks! :-)

**Comment by Alewx** [comment]
done in https://github.com/Alewx/UbioWeldContinued/commit/248a5e8d7a2caa225f20d6b1b545b1ef901a5abf
