### ISSUE TITLE
Support for ModularFuelTanks

### ISSUE THREAD

**Issue by dertroglodyt** [UbioWeldingLtd/UbioWeldContinued#34]

**Comment by Alewx** [comment]
Do you have InterstellarFuelswitch and MFT in the same game?

**Comment by dertroglodyt** [comment]
Yep. Is that good or bad?

**Comment by Alewx** [comment]
Don't know mine just does not work with it.

**Comment by dertroglodyt** [comment]
Seem to work for me. But hard to tell if there are any side effects. I have around 150 mods in my regular install.
Actually I don't know anything about InterstellarFuelswitch apart from the two tanks. Was some dependence of another mod.

**Comment by Alewx** [comment]
After the release, after it.
