### ISSUE TITLE
Weldment gets angles wrong

### ISSUE THREAD

**Issue by KAmaia** [UbioWeldingLtd/UbioWeldContinued#43]
Anytime I weld an edge connected part such as a structrual panel or wing connecter the saved/loaded part is offset from it's connecting node, and the angle is reset on me.

**Comment by Alewx** [comment]
could you provide an example craft?

**Comment by rkagerer** [comment]
Not sure but I wonder if it could be related to [this](http://forum.kerbalspaceprogram.com/index.php?/topic/96670-12-ubiozur-welding-ltd-continued-234-2016-10-16/&do=findComment&comment=2831404)?
