### ISSUE TITLE
Hint box is too small for "Select partbranch" description in 2.1.x

### ISSUE THREAD

**Issue by girka2k** [UbioWeldingLtd/UbioWeldContinued#7]
or description is too long for box... :)

![2015-01-15 20-37-51 kerbal space program](https://cloud.githubusercontent.com/assets/6450733/5761704/34fa1e82-9cee-11e4-91eb-97243a792ea5.png)

**Comment by Alewx** [comment]
fixed in https://github.com/UbioWeldingLtd/UbioWeldContinued/commit/12f83d9eecfc0b56efd6aab072b9a535b09b014f
