### ISSUE TITLE
"it would be nice if the welding dialog had some kind of 'close' button on it"

### ISSUE THREAD

**Issue by girka2k** [UbioWeldingLtd/UbioWeldContinued#8]
"...it would be nice if the welding dialog had some kind of 'close' button on it. I know I can click the welding icon on the toolbar, but having another button on the dialog would be a nice touch."
-Redchrome

http://forum.kerbalspaceprogram.com/threads/107273-0-90-UbioZur-Welding-Ltd-Continued-2-1-1-%282015-01-14%29?p=1669972&viewfull=1#post1669972

**Comment by Alewx** [comment]
fixed in https://github.com/UbioWeldingLtd/UbioWeldContinued/commit/8eb95dc3c992c486f077c52f562a13872ec27d27
